import React, { useState, useEffect } from "react";
import Header from "../components/Header/Header";
import Breadcrumbs from "../components/ShoppingCart/BreadCrumbs";
import Footer from "../components/Footer";
import ShopServices from "../components/ads/ShopServices";
import CajaList from "../components/Cajas/CajaList";
import CajaCreateModal from "../components/Cajas/Modals/CajaCreateModal";
import CajaEditModal from "../components/Cajas/Modals/CajaEditModal";
import CajaDeleteModal from "../components/Cajas/Modals/CajaDeleteModal";

const CajasEditListPage = () => {
  const [cajas, setCajas] = useState([]);
  const [sucursales, setSucursales] = useState([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [currentCaja, setCurrentCaja] = useState(null);

  useEffect(() => {
    // Fetch cajas and sucursales from your API here
    // For now, we'll use mock data
    setCajas([
      {
        id: 1,
        numero: 3,
        id_sucursal: {
          id: 1,
          nombre: "equipetrol",
          direccion: "barrio equipetrols",
        },
      },
    ]);
    setSucursales([
      { id: 1, nombre: "equipetrol", direccion: "barrio equipetrols" },
      { id: 2, nombre: "centro", direccion: "calle 24 de septiembre" },
    ]);
  }, []);

  const handleShowCreateModal = () => setShowCreateModal(true);
  const handleCloseCreateModal = () => setShowCreateModal(false);

  const handleShowEditModal = (caja) => {
    setCurrentCaja(caja);
    setShowEditModal(true);
  };
  const handleCloseEditModal = () => {
    setShowEditModal(false);
    setCurrentCaja(null);
  };

  const handleShowDeleteModal = (caja) => {
    setCurrentCaja(caja);
    setShowDeleteModal(true);
  };
  const handleCloseDeleteModal = () => {
    setShowDeleteModal(false);
    setCurrentCaja(null);
  };

  const handleSaveCaja = (cajaData) => {
    // Here you would typically send a POST or PUT request to your API
    if (cajaData.id) {
      setCajas(
        cajas.map((c) =>
          c.id === cajaData.id
            ? {
                ...c,
                ...cajaData,
                id_sucursal: sucursales.find(
                  (s) => s.id === parseInt(cajaData.id_sucursal)
                ),
              }
            : c
        )
      );
    } else {
      const newCaja = {
        id: Date.now(), // This should be generated by the backend in a real scenario
        numero: parseInt(cajaData.numero),
        id_sucursal: sucursales.find(
          (s) => s.id === parseInt(cajaData.id_sucursal)
        ),
      };
      setCajas([...cajas, newCaja]);
    }
    handleCloseCreateModal();
    handleCloseEditModal();
  };

  const handleDeleteCaja = () => {
    // Here you would typically send a DELETE request to your API
    setCajas(cajas.filter((c) => c.id !== currentCaja.id));
    handleCloseDeleteModal();
  };

  return (
    <>
      <Header />
      <Breadcrumbs current="Lista de Cajas" />
      <div
        className="container"
        style={{ marginTop: "50px", textAlign: "right" }}
      >
        <button
          onClick={handleShowCreateModal}
          className="btn"
          style={{ backgroundColor: "green", color: "white" }}
        >
          Crear Caja
        </button>
      </div>
      <CajaList
        cajas={cajas}
        onEdit={handleShowEditModal}
        onDelete={handleShowDeleteModal}
      />
      <ShopServices />
      <div style={{ margin: "150px 0px" }}></div>
      <Footer />

      <CajaCreateModal
        open={showCreateModal}
        onClose={handleCloseCreateModal}
        onSave={handleSaveCaja}
        sucursales={sucursales}
      />
      <CajaEditModal
        open={showEditModal}
        onClose={handleCloseEditModal}
        onSave={handleSaveCaja}
        caja={currentCaja}
        sucursales={sucursales}
      />
      <CajaDeleteModal
        open={showDeleteModal}
        onClose={handleCloseDeleteModal}
        onConfirm={handleDeleteCaja}
        cajaNumero={currentCaja?.numero}
      />
    </>
  );
};

export default CajasEditListPage;
