import React, { useState, useEffect } from "react";
import Header from "../components/Header/Header";
import Breadcrumbs from "../components/ShoppingCart/BreadCrumbs";
import Footer from "../components/Footer";
import ShopServices from "../components/ads/ShopServices";
import SucursalDeleteModal from "../components/Sucursales/Modals/SucursalDeleteModal";
import SucursalEditModal from "../components/Sucursales/Modals/SucursalEditModal";
import SucursalCreateModal from "../components/Sucursales/Modals/SucursalCreateModal";
import SucursalList from "../components/Sucursales/SucursalList";

const SucursalesEditListPage = () => {
  const [sucursales, setSucursales] = useState([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [currentSucursal, setCurrentSucursal] = useState(null);

  useEffect(() => {
    // Fetch sucursales from your API here
    // For now, we'll use mock data
    setSucursales([
      { id: 1, nombre: "equipetrol", direccion: "barrio equipetrols" },
      { id: 2, nombre: "centro", direccion: "calle 24 de septiembre" },
    ]);
  }, []);

  const handleShowCreateModal = () => setShowCreateModal(true);
  const handleCloseCreateModal = () => setShowCreateModal(false);

  const handleShowEditModal = (sucursal) => {
    setCurrentSucursal(sucursal);
    setShowEditModal(true);
  };
  const handleCloseEditModal = () => {
    setShowEditModal(false);
    setCurrentSucursal(null);
  };

  const handleShowDeleteModal = (sucursal) => {
    setCurrentSucursal(sucursal);
    setShowDeleteModal(true);
  };
  const handleCloseDeleteModal = () => {
    setShowDeleteModal(false);
    setCurrentSucursal(null);
  };

  const handleSaveSucursal = (sucursalData) => {
    // Here you would typically send a POST or PUT request to your API
    if (sucursalData.id) {
      setSucursales(
        sucursales.map((s) => (s.id === sucursalData.id ? sucursalData : s))
      );
    } else {
      const newSucursal = {
        id: Date.now(), // This should be generated by the backend in a real scenario
        ...sucursalData,
      };
      setSucursales([...sucursales, newSucursal]);
    }
    handleCloseCreateModal();
    handleCloseEditModal();
  };

  const handleDeleteSucursal = () => {
    // Here you would typically send a DELETE request to your API
    setSucursales(sucursales.filter((s) => s.id !== currentSucursal.id));
    handleCloseDeleteModal();
  };

  return (
    <>
      <Header />
      <Breadcrumbs current="Lista de Sucursales" />
      <div
        className="container"
        style={{ marginTop: "50px", textAlign: "right" }}
      >
        <button
          onClick={handleShowCreateModal}
          className="btn"
          style={{ backgroundColor: "green", color: "white" }}
        >
          Crear Sucursal
        </button>
      </div>
      <SucursalList
        sucursales={sucursales}
        onEdit={handleShowEditModal}
        onDelete={handleShowDeleteModal}
      />
      <ShopServices />
      <div style={{ margin: "150px 0px" }}></div>
      <Footer />

      <SucursalCreateModal
        open={showCreateModal}
        onClose={handleCloseCreateModal}
        onSave={handleSaveSucursal}
      />
      <SucursalEditModal
        open={showEditModal}
        onClose={handleCloseEditModal}
        onSave={handleSaveSucursal}
        sucursal={currentSucursal}
      />
      <SucursalDeleteModal
        open={showDeleteModal}
        onClose={handleCloseDeleteModal}
        onConfirm={handleDeleteSucursal}
        sucursalName={currentSucursal?.nombre}
      />
    </>
  );
};

export default SucursalesEditListPage;
